name: Checks

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: Copy Example Files
        run: |
          cp config/options.example.ts config/options.ts
          cp lib/badlinks-secret.example.ts lib/badlinks-secret.ts

      - name: ESLint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Dry Run
        run: yarn start:dry

  check-format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: Prettier Check
        run: yarn format:check
